import type { Metadata, Viewport } from 'next';
//import localFont from 'next/font/local';
import { Montserrat } from 'next/font/google';
import './scss/style.scss';
import { ThemeProvider } from '@/components/theme-provider';

const montserrat = Montserrat({
    subsets: ['latin'],
    display: 'swap',
});
/*
const geistSans = localFont({
	src: './fonts/GeistVF.woff',
	variable: '--font-geist-sans',
	weight: '100 900',
});
const geistMono = localFont({
	src: './fonts/GeistMonoVF.woff',
	variable: '--font-geist-mono',
	weight: '100 900',
});
*/
export const viewport: Viewport = {
    initialScale: 1,
    width: 'device-width',
};

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={montserrat.className}>
                <ThemeProvider
                    attribute="class"
                    defaultTheme="dark"
                    enableSystem
                    disableTransitionOnChange
                >
                    {children}
                </ThemeProvider>
            </body>
        </html>
    );
}
