x-minio-common: &minio-common
  image: quay.io/minio/minio:latest
  command: server --console-address ":9090" /data
  ports:
    - "9000:9000"
    - "9090:9090"
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  backend:
    profiles:
      - prod
    build:
      context: ./backend
    ports:
      - "8080:8080"
    env_file:
      - .env.backend
    depends_on:
      - db

  frontend:
    profiles:
      - prod
    build:
      context: ./frontend
    env_file:
      - .env.local
    ports:
      - "3000:3000"
  db:
    image: postgres:17.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: szakdolgozat
      POSTGRES_DB: saturn_db
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  minio:
    <<: *minio-common
    hostname: minio
    environment:
      MINIO_SERVER_URL: http://localhost:9000
      MINIO_PUBLIC_URL: http://localhost:9000
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - minio_data:/data

  nginx-dev:
    image: nginx:latest
    volumes:
      - ./nginx/dev:/etc/nginx/templates
    ports:
      - "80:80"

volumes:
  postgres_data:
  minio_data:
