x-minio-common: &minio-common
  image: quay.io/minio/minio:latest
  command: server --console-address ":9090" /data
  ports:
    - "9000:9000"
    - "9090:9090"
  healthcheck:
    test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
    interval: 30s
    timeout: 20s
    retries: 3

services:
  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/saturn_db
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  db:
    image: postgres:17.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: szakdolgozat
      POSTGRES_DB: saturn_db
    volumes:
      - "postgres_data:/var/lib/postgresql/data"

  minio:
    <<: *minio-common
    hostname: minio
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  minio_data:
