services:
  backend:
    container_name: backend
    profiles:
      - prod
    build:
      context: ./backend
    environment:
      - DB_PORT=${DB_PORT}
      - DB_URL=${DB_URL}
      - DB_NAME=${DB_NAME}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GITHUB_CLIENT_ID=${GITHUB_CLIENT_ID}
      - GITHUB_CLIENT_SECRET=${GITHUB_CLIENT_SECRET}
      - JWT_ACCESS_KEY=${JWT_ACCESS_KEY}
      - JWT_REFRESH_KEY=${JWT_REFRESH_KEY}
      - JWT_ACCESS_KEY_EXPIRATION_TIME=${JWT_ACCESS_KEY_EXPIRATION_TIME}
      - JWT_REFRESH_KEY_EXPIRATION_TIME=${JWT_REFRESH_KEY_EXPIRATION_TIME}
      - MINIO_URL=${MINIO_URL}
      - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
      - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
      - MINIO_BUCKET_NAME=${MINIO_BUCKET_NAME}
      - MINIO_EXPIRY_TIME_IN_MINUTES=${MINIO_EXPIRY_TIME_IN_MINUTES}
      - HOST=${HOST}
    depends_on:
      - db
    healthcheck:
      test: "curl --fail --silent ${BACKEND_HOST}:${BACKEND_PORT}/api/actuator/health | grep UP || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      - default

  frontend:
    container_name: frontend
    profiles:
      - prod
    build:
      context: ./frontend
    healthcheck:
      test: "curl -f http://${FRONTEND_HOST}:${FRONTEND_PORT}/api/health || exit 1"
      interval: 20s
      timeout: 5s
      retries: 5
      start_period: 40s
    networks:
      - default

  db:
    container_name: db
    image: postgres:17.4
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: saturn_db
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    networks:
      - default

  minio:
    container_name: minio
    image: quay.io/minio/minio:latest
    command: server --console-address ":9090" /data
    ports:
      - "9000:9000"
      - "9090:9090"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://minio:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - default

  nginx-prod:
    container_name: nginx
    image: nginx:latest
    profiles:
      - prod
    volumes:
      - ./nginx/default.conf.prod.template:/etc/nginx/templates/default.conf.template
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    environment:
      - NGINX_PORT=${NGINX_PORT}
      - FRONTEND_HOST=${FRONTEND_HOST}
      - FRONTEND_PORT=${FRONTEND_PORT}
      - BACKEND_HOST=${BACKEND_HOST}
      - BACKEND_PORT=${BACKEND_PORT}
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend

    networks:
      - default

volumes:
  postgres_data:
  minio_data:

networks:
  default:
    name: szakdolgozat
    driver: bridge
