CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) PRIMARY KEY,
    firstname VARCHAR(50) NOT NULL,
    lastname VARCHAR(50) NOT NULL,
    email VARCHAR(100) NOT NULL UNIQUE ,
    password TEXT NOT NULL,
    registered_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    profile_picture_url TEXT,
    role VARCHAR(50),
    verified BOOLEAN,
    provider VARCHAR(50) DEFAULT 'EMAIL' NOT NULL
);

CREATE TABLE projects (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) PRIMARY KEY,
    name VARCHAR(50),
    key VARCHAR(10) NOT NUll,
    description TEXT,
    status VARCHAR(30),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ticket_counter BIGINT DEFAULT 0,
    owner_id BIGINT REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE tickets (
    id BIGINT,
    title VARCHAR(150),
    description TEXT,
    priority VARCHAR(30),
    status VARCHAR(30),
    issue_type VARCHAR(30),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT  CURRENT_TIMESTAMP,
    assignee_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    reporter_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
    PRIMARY KEY (id, project_id)
);

CREATE TABLE sprints (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) PRIMARY KEY,
    number BIGINT NOT NULL,
    start_date TIMESTAMP,
    end_date TIMESTAMP,
    project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE
);

CREATE TABLE activity_log (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) PRIMARY KEY,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    activity VARCHAR(100),
    timestamp TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ticket_id BIGINT,
    project_id BIGINT,
    FOREIGN KEY (ticket_id, project_id) REFERENCES tickets(id, project_id) ON DELETE CASCADE
);

CREATE TABLE comments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) PRIMARY KEY,
    content TEXT,
    user_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
    ticket_id BIGINT,
    project_id BIGINT,
    FOREIGN KEY (ticket_id, project_id) REFERENCES tickets(id, project_id) ON DELETE CASCADE
);


CREATE TABLE user_projects (
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
    role VARCHAR(50) NOT NULL,
    PRIMARY KEY (user_id, project_id)
);

CREATE TABLE pinned_projects (
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE,
    project_id BIGINT REFERENCES projects(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, project_id)
);

CREATE TABLE connected_accounts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) PRIMARY KEY,
    provider VARCHAR(255),
    provider_id VARCHAR(255),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE verification_code (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) PRIMARY KEY,
    code VARCHAR(255) NOT NULL,
    email_sent BOOLEAN NOT NULL DEFAULT FALSE,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE password_reset_token (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY (START WITH 1001) PRIMARY KEY,
    token VARCHAR(255) NOT NULL,
    email_sent BOOLEAN NOT NULL DEFAULT FALSE,
    expires_at TIMESTAMP NOT NULL,
    user_id BIGINT REFERENCES users(id) ON DELETE CASCADE
);