name: Build and push backend and frontend changes

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push backend image
        run: |
          docker build -t docker.io/${{ secrets.DOCKERHUB_USERNAME }}/backend:latest ./backend
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/backend:latest

      - name: Build and push frontend image
        run: |
          docker build -t docker.io/${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest ./frontend
          docker push docker.io/${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
